-- Auto-generated by gen.lua

local TW = {}

local S = {}
local T = {}
for i=1,6 do T[i] = 0 end
local function C(x) return x and 1 or 0 end

local min = math.min

function INTERNAL_CIRCUITS.Solve(Train,Triggers)
	local P		= Train.PositionSwitch.SelectedPosition
	local RK	= Train.RheostatController.SelectedPosition
	local B		= (Train.Battery.Voltage > 55) and 1 or 0
	
	-- Solve all circuits
	T["SDRK_ShortCircuit"] = -10*Train.RheostatController.RKP*(Train.RUT.Value+Train.RRT.Value+(1.0-Train.SR1.Value))
	S["33-33Aa"] = Train.KD.Value+1
	S["33-33Aa"] = Train.VAD.Value+S["33-33Aa"]
	S["U2-20"] = Train.KV["U2-20a"]+Train.KV["U2-20b"]
	S["D1-31V"] = Train.KDL.Value+Train.VDL.Value
	S["10AK-VAH1"] = Train.VAH.Value+Train.RPB.Value
	S["33B-33AVU"] = Train.AVU.Value+Train.OtklAVU.Value
	S["1T-1P"] = Train.NR.Value+Train.RPU.Value
	S["2Zh-2A"] = (1.0-Train.KSB1.Value)+(1.0-Train.TR1.Value)
	S["2Zh-2A"] = S["2Zh-2A"]+Train.KSB2.Value
	S["8A-8Ye"] = C(RK == 1)+(1.0-Train.LK4.Value)
	S["10AYa-10E"] = (1.0-Train.LK3.Value)+Train.Rper.Value
	S["10AP-10AD"] = Train.LK2.Value+C((P == 3) or (P == 4))
	S["10AE-10B"] = Train.TR1.Value+Train.RV1.Value
	S["10AE-10B"] = Train.RV1.Value+S["10AE-10B"]
	S["1A-1R"] = (1.0-Train.RV1.Value)*C((P == 1))+C((RK >= 1) and (RK <= 5))*C((P == 2))
	S["1Yu-1E"] = Train.KSB1.Value*Train.KSB2.Value+Train.KSH2.Value
	S["2G-2V"] = Train.KSH1.Value*C((RK >= 2) and (RK <= 4))+C((RK >= 5) and (RK <= 18))
	S["2G-2A"] = S["2G-2V"]*C((P == 2) or (P == 4))+C((P == 1) or (P == 3))*C((RK >= 1) and (RK <= 17))
	S["10AG-10AD"] = Train.TR1.Value*C((P == 1) or (P == 2) or (P == 4))*Train.TR2.Value+(1.0-Train.TR1.Value)*C((P == 2) or (P == 3) or (P == 4))*(1.0-Train.TR2.Value)
	S["10E-10AG"] = (1.0-Train.LK1.Value)*S["10AP-10AD"]*S["10AG-10AD"]+C((P == 1))*Train.LK3.Value*C(RK == 18)
	S["10Zh-10N"] = Train.SR1.Value*(1.0-Train.RUT.Value)*(1.0-Train.RRT.Value)+Train.RheostatController.RKM
	S["1Zh-1G"] = Train.LK2.Value*C((P == 1) or (P == 3))*C(RK == 1)*S["1Yu-1E"]+Train.LK3.Value
	S["10"] = 1*Train:ReadTrainWire(10)
	S["FR1"] = S["10"]*Train.KV["FR1-10"]
	S["FR1/2"] = S["10"]*Train.KV["FR1-10"]
	S["F7"] = S["10"]*Train.KV["F7-10"]
	S["8"] = S["10"]*Train.KV["10-8"]
	S["1A"] = Train.A1.Value*Train:ReadTrainWire(1)
	S["2Ye"] = Train.A2.Value*S["2Zh-2A"]*Train.LK4.Value*S["2G-2A"]*Train:ReadTrainWire(2)+T[2]*(1.0-Train.LK4.Value)
	S["B2"] = 1*Train.VB.Value*B
	S["F8"] = S["10"]*Train.KV["F7-10"]*Train.VUS.Value
	S["3A"] = Train.A3.Value*Train:ReadTrainWire(3)
	S["4B"] = (1.0-Train.RKR.Value)*Train:ReadTrainWire(4)
	S["5B"] = Train.RKR.Value*Train:ReadTrainWire(5)
	S["5V"] = Train.RKR.Value*Train:ReadTrainWire(4)+T[6]*(1.0-Train.RKR.Value)
	S["5B'"] = S["5V"]*Train.LK3.Value
	S["6A"] = Train.A6.Value*Train:ReadTrainWire(6)
	S["8A"] = Train.A8.Value*Train:ReadTrainWire(8)
	S["B12"] = 1*Train.VB.Value*B
	S["18A"] = S["B2"]*Train.LK4.Value*(1.0-Train.RPvozvrat.Value)*Train.A14.Value
	S["1R"] = S["1A"]*S["1A-1R"]
	S["24V"] = (1.0-Train.LK4.Value)*Train:ReadTrainWire(24)
	S["25A"] = Train.A25.Value*Train:ReadTrainWire(25)
	S["27A"] = Train.A50.Value*Train:ReadTrainWire(27)
	S["28A"] = Train.A51.Value*Train:ReadTrainWire(28)
	S["10AYa"] = S["B2"]*Train.A80.Value
	S["10AE"] = S["B2"]*Train.A30.Value
	S["8Zh"] = S["8A"]*C((RK >= 17) and (RK <= 18))
	S["1-7R-29"] = S["B2"]*Train.A44.Value*Train.RezMK.Value
	S["10B"] = S["10AE"]*S["10AE-10B"]
	S["8G"] = S["8A"]*S["8A-8Ye"]*(1.0-Train.RT2.Value)
	S["10AV"] = S["10AYa"]*C((RK >= 2) and (RK <= 18))*(1.0-Train.LK3.Value)
	S["22A"] = Train.A23.Value*1*Train:ReadTrainWire(23)+T[4]*Train.A22.Value
	S["18Aa"] = S["B2"]*(1.0-Train.RPvozvrat.Value)*Train.A14.Value
	S["17A"] = Train.A17.Value*Train:ReadTrainWire(17)
	S["10AL"] = S["10"]*Train.VU.Value
	S["10ALa"] = S["10AL"]*Train.A64.Value
	S["Sh1-43"] = S["10AL"]*Train.A45.Value
	S["10AS"] = S["10AL"]*Train.A55.Value
	S["10AK"] = S["10AL"]*Train.A54.Value
	S["6Yu"] = S["6A"]*C((RK >= 1) and (RK <= 5))*C((P == 3) or (P == 4))
	S["10AG"] = S["10AYa"]*S["10AYa-10E"]*S["10E-10AG"]
	S["1-7R-8"] = S["10AS"]*Train.KV["10AS-U4"]*Train.VozvratRP.Value
	S["33V"] = S["10AK"]*S["10AK-VAH1"]*Train.RV2.Value*1*S["33B-33AVU"]
	S["10N"] = S["10AE"]*1*S["10Zh-10N"]+T["SDRK_ShortCircuit"]
	S["20B"] = Train.A20.Value*(1.0-Train.RPvozvrat.Value)*Train:ReadTrainWire(20)
	S["10/4"] = S["B12"]*Train.VB.Value*Train.A56.Value
	S["F10"] = Train.A47.Value*Train:ReadTrainWire("F8")
	S["F13"] = Train.A46.Value*Train:ReadTrainWire("F7")
	S["10I"] = S["10AE"]*Train.RheostatController.RKM
	S["B8"] = S["B2"]*Train.A53.Value
	S["B22"] = S["B8"]*Train.A75.Value
	S["B28"] = S["B8"]*Train.KUP.Value
	S["36Ya"] = S["B8"]*Train.KVC.Value
	S["B13"] = S["B12"]*Train.A24.Value
	S["22K"] = S["10/4"]*Train.A10.Value
	S["U0"] = S["10/4"]*Train.A27.Value
	S["s3"] = S["U0"]*Train.DIPon.Value
	S["s10"] = S["U0"]*Train.DIPoff.Value
	S["C3"] = S["10/4"]*Train.KV["10/4-C3"]
	S["F1"] = S["10/4"]*Train.KV["10/4-F1"]
	S["4"] = S["10AK"]*Train.KV["10AK-4"]
	S["5"] = S["10AK"]*Train.KV["10AK-5"]
	S["U2"] = S["10AS"]*Train.KV["U2-10AS"]
	S["24"] = S["U2"]*Train.KSN.Value
	S["2-7R-21"] = S["U2"]*1+(-10*Train:ReadTrainWire(18))
	S["2"] = S["10AK"]*Train.KV["10AK-2"]
	S["3"] = S["U2"]*Train.KV["U2-3"]
	S["1P"] = S["1A"]*S["1T-1P"]*C((P == 1) or (P == 2))+T[1]*C((P == 3) or (P == 4))
	S["22V"] = S["22A"]*(1.0-Train.TRK.Value)
	S["1Zh"] = S["1P"]*Train.AVT.Value*(1.0-Train.RPvozvrat.Value)*S["1Zh-1G"]
	S["20"] = S["U2"]*S["U2-20"]
	S["22E'"] = S["10/4"]*Train.VMK.Value*Train.AK.Value
	S["10AH"] = S["10I"]*(1.0-Train.LK1.Value)
	S["10H"] = S["10I"]*Train.LK4.Value
	S["33Aa"] = S["10AS"]*Train.KV["10AS-33"]*S["33-33Aa"]
	S["1"] = S["10AS"]*Train.KV["10AS-33D"]*Train.R1_5.Value
	S["1N"] = S["1Zh"]*C((P == 1) or (P == 3))
	S["33G"] = S["U2"]*Train.KV["U2-33G"]
	S["6"] = S["10AL"]*Train.A61.Value*Train.RVT.Value
	S["D1"] = S["10/4"]*Train.A21.Value*Train.KV["D-D1"]
	S["12"] = S["D1"]*Train.KRZD.Value
	S["32V"] = S["D1"]*Train.KDP.Value
	S["25"] = S["U2"]*Train.KV["U2-25"]*1
	S["16"] = S["D1"]*Train.VUD1.Value*Train.VUD2.Value
	S["1K"] = S["1Zh"]*C((P == 1) or (P == 2))
	S["31V"] = S["D1"]*S["D1-31V"]
	S["F2a"] = Train.A7.Value*Train:ReadTrainWire("F1")
	S["F1a"] = Train.A9.Value*Train:ReadTrainWire("F1")
	S["U0a"] = S["U0"]*1+(-10*Train:ReadTrainWire("10AH"))

	-- Call all triggers
	Triggers["XT3.1"](S["B13"])
	Train.PneumaticNo2:TriggerInput("Set",S["8G"])
	Train.Panel["HeadLights2"] = S["F13"]
	Train.RR:TriggerInput("Set",S["1N"])
	Train:WriteTrainWire(20,S["20"])
	Train.Panel["V1"] = S["10/4"]
	Train.Panel["EmergencyLight"] = S["B12"]
	Triggers["KPP"](S["27A"])
	Train:WriteTrainWire(32,S["32V"])
	Train:WriteTrainWire(31,S["31V"])
	Triggers["KSH1"](S["1R"])
	Train:WriteTrainWire(25,S["25"])
	Train.R1_5:TriggerInput("Set",S["33V"])
	Train.LK1:TriggerInput("Set",S["1K"])
	Triggers["ReverserBackward"](S["4B"])
	Train:WriteTrainWire(12,S["12"])
	Train:WriteTrainWire(6,S["6"])
	Train:WriteTrainWire(16,S["16"])
	Triggers["KSB2"](S["6Yu"])
	T[4] = min(1,Train:ReadTrainWire(22))
	Train.KK:TriggerInput("Set",S["22V"])
	Train.RPU:TriggerInput("Set",S["27A"])
	Train.LK3:TriggerInput("Set",S["1Zh"])
	T[5] = min(1,S["5V"])
	Train.Panel["HeadLights1"] = S["F10"]
	Train:WriteTrainWire("F8",S["F8"])
	Train:WriteTrainWire("C3",S["C3"])
	Train.Panel["RedRP"] = S["2-7R-21"]
	Train.RV1:TriggerInput("Set",S["2Ye"])
	Train:WriteTrainWire(3,S["3"])
	Train:WriteTrainWire(28,S["s10"])
	Train:WriteTrainWire("F1",S["F1"])
	Train.LK4:TriggerInput("Set",S["5B'"])
	Triggers["RRTpod"](S["10AH"])
	Triggers["XR3.4"](S["36Ya"])
	Triggers["SDPP"](S["10AG"])
	T[6] = min(1,Train:ReadTrainWire(5))
	Train.Panel["KUP"] = S["B28"]
	T[3] = min(1,S["22A"])
	Train.RZ_2:TriggerInput("Set",S["24V"])
	Triggers["KSH2"](S["1R"])
	Train:WriteTrainWire(22,S["22E'"])
	T[2] = min(1,S["10AV"])
	Train:WriteTrainWire(23,S["1-7R-29"])
	Train:WriteTrainWire(2,S["2"])
	Train:WriteTrainWire(8,S["8"])
	Train:WriteTrainWire("F7",S["F7"])
	Train:WriteTrainWire(1,S["1"])
	Triggers["ReverserForward"](S["5B"])
	Triggers["XR3.2"](S["27A"])
	Train:WriteTrainWire(9,S["10/4"])
	Triggers["RUTpod"](S["10H"])
	Train.RVT:TriggerInput("Set",S["33G"])
	Train.Panel["RedLightRight"] = S["F2a"]
	Triggers["RRTuderzh"](S["25A"])
	Train:WriteTrainWire("10AH",S["18Aa"])
	Triggers["SDRK_Coil"](S["10B"])
	Train:WriteTrainWire(4,S["4"])
	Triggers["XR3.6"](S["36Ya"])
	Triggers["LK5"](S["20B"])
	Train.Panel["RedLightLeft"] = S["F1a"]
	Train.LK2:TriggerInput("Set",S["20B"])
	Triggers["XR3.3"](S["28A"])
	Train:WriteTrainWire(18,S["18A"])
	Triggers["RPvozvrat"](S["17A"])
	Train.PneumaticNo1:TriggerInput("Set",S["8Zh"])
	Triggers["XR3.7"](S["36Ya"])
	Train.Rper:TriggerInput("Set",S["3A"])
	Train.Panel["HeadLights3"] = S["F13"]
	Train:WriteTrainWire(10,S["10/4"])
	T[1] = min(1,S["6A"])
	Triggers["KSB1"](S["6Yu"])
	Train:WriteTrainWire(27,S["s3"])
	Train:WriteTrainWire(24,S["24"])
	Train.TR2:TriggerInput("Set",S["6A"])
	Train.TR1:TriggerInput("Set",S["6A"])
	Triggers["SDRK"](S["10N"])
	Train.KVC:TriggerInput("Set",S["B8"])
	Train:WriteTrainWire(17,S["1-7R-8"])
	Train.Panel["GreenRP"] = S["U0a"]
	Train:WriteTrainWire(5,S["5"])
	Train.RUP:TriggerInput("Set",S["6Yu"])
	Train.KUP:TriggerInput("Set",S["B22"])
	Train.SR1:TriggerInput("Set",S["2Ye"])
	Train.RV2:TriggerInput("Set",S["33Aa"])
	Train.Panel["CabinLight"] = S["10ALa"]
	return S
end