--------------------------------------------------------------------------------
-- Тяговый электродвигатель постоянного тока (ДК-117ДМ)
--------------------------------------------------------------------------------
Metrostroi.DefineSystem("DK_117DM")

function TRAIN_SYSTEM:Initialize()	
	-- Speed of train in km/h
	self.Speed = 0
	
	-- Winding resistance
	self.Rw = 0.0691*0.5 -- Ohms, (half because this value was actually resistance of GROUP of engines)
	
	-- Voltage generated by engine
	self.E13 = 0.0 -- Volts
	self.E24 = 0.0 -- Volts
	
	-- Rotation rate
	self.RotationRate = 0.0
	
	-- Magnetic flux in the engine
	self.MagneticFlux13 = 0.0
	self.MagneticFlux24 = 0.0
	
	-- Field reduction (how much current goes through stator)
	self.FieldReduction13 = 0.0
	self.FieldReduction24 = 0.0
	
	-- Moment generated by the engine
	self.Moment13 = 0.0
	self.Moment24 = 0.0
	self.BogeyMoment = 0.0 -- Moment on front and rear bogey is equal
	
	-- Need many iterations for engine simulation to converge
	self.SubIterations = 16
end

function TRAIN_SYSTEM:Inputs()
	return { "Speed" }
end

function TRAIN_SYSTEM:Outputs()
	return { "MagneticFlux13", "MagneticFlux24", "RotationRate", 
			 "E13", "E24", "Moment13", "Moment24",
			 "FieldReduction13","FieldReduction24",
			 "BogeyMoment" }
end

function TRAIN_SYSTEM:TriggerInput(name,value)
	if name == "Speed" then
		self.Speed = value
	end
end

function TRAIN_SYSTEM:Think(dT)
	local Train = self.Train

	-- Get rate of engine rotation
	local currentRotationRate = 2500 * (self.Speed/80)
	self.RotationRate = self.RotationRate + 5.0 * (currentRotationRate - self.RotationRate) * dT
	
	-- Engine constants
	local A = 0.477
	local B = 1.500
	local M = 1.32e-2

	-- Calculate magnetic flux in the engine
	self.MagneticFlux13 = A*(1-math.exp(-B*Train.Electric.Istator13/100))
	self.MagneticFlux24 = A*(1-math.exp(-B*Train.Electric.Istator24/100))

	self.MagneticFlux13 = math.min(8.0,math.max(0.001,self.MagneticFlux13))
	self.MagneticFlux24 = math.min(8.0,math.max(0.001,self.MagneticFlux24))
	
	-- Calculate voltage generated by engines from magnetic flux
	self.E13 = self.RotationRate * self.MagneticFlux13
	self.E24 = self.RotationRate * self.MagneticFlux24
	
	self.E13 = math.max(-4000,math.min(4000,self.E13))
	self.E24 = math.max(-4000,math.min(4000,self.E24))

	-- Calculate engine force (moment)
	self.Moment13 = M * Train.Electric.I13 * self.MagneticFlux13
	self.Moment24 = M * Train.Electric.I24 * self.MagneticFlux24
	
	-- Apply moment to bogeys
	if (math.abs(Train.Electric.I13) > 1.0) or (math.abs(Train.Electric.I24) > 1.0) then
		self.BogeyMoment = (self.Moment13 + self.Moment24) / 2
	else
		self.BogeyMoment = 0.0
	end
	
	-- Calculate reduction in magnetic field
	self.FieldReduction13 = math.abs(100 * Train.Electric.Istator13 / (Train.Electric.I13+1e-9))
	self.FieldReduction24 = math.abs(100 * Train.Electric.Istator24 / (Train.Electric.I24+1e-9))
end
