--------------------------------------------------------------------------------
-- Тяговый электродвигатель постоянного тока (ДК-117ДМ)
--------------------------------------------------------------------------------
Metrostroi.DefineSystem("DK_117DM")

function TRAIN_SYSTEM:Initialize()
	self.Name = "DK_117DM"
	
	-- Winding resistance
	self.Rw = 0.100 -- Ohms
	
	-- Total current through anchor sensed by РУТ
	self.RUTCurrent = 0.0
end

function TRAIN_SYSTEM:Inputs()
	return { }
end

function TRAIN_SYSTEM:Outputs()
	return { }
end

function TRAIN_SYSTEM:Think()
	local Train = self.Train
	
	-- Calculate engine rotation speed and magnetic flux
	local magneticFlux13 = 1.0
	local magneticFlux24 = 1.0
	local rotationRate = 4000 * ((Train.FrontBogey.Speed + Train.RearBogey.Speed)/90) / 2
	
	if Train.RheostatController.Position > 2.5 then
		magneticFlux13 = 1.00
		magneticFlux24 = 1.00
	else
		magneticFlux13 = 0.35
		magneticFlux24 = 0.35
	end
	
	-- Calculate voltage generated by engines from magnetic flux
	local E13 = 0.30 * rotationRate * magneticFlux13
	local E24 = 0.30 * rotationRate * magneticFlux24

	-- Series connection
	if true then
		-- Total voltage over entire circuit
		local totalV = Train.Electric.Power750V * Train.LK3.Value * Train.LK4.Value
		-- Calculate total resistance of the circuit
		local totalR = Train.Electric.Block1Resistance + Train.Electric.Block2Resistance + 2 * self.Rw
		
		-- Calculate current flowing through anchors
		local Ianchor = (totalV - E13 - E24) / (totalR)
		self.RUTCurrent = Ianchor
		
		-- Calculate voltage drop over each motor
		local MVoltage = Ianchor * (self.Rw / (Train.Electric.Block1Resistance + Train.Electric.Block2Resistance + self.Rw))
	
		-- Calculate engine force (moment)
		local Moment13 = (1.0/170000.0) * (Ianchor^2) --/ magneticFlux13
		local Moment24 = (1.0/170000.0) * (Ianchor^2) --/ magneticFlux24
		if Ianchor < 0.0 then Moment13 = - Moment13 end
		if Ianchor < 0.0 then Moment24 = - Moment24 end
		
		-- Calculate total power radiation
		local Presistance = Ianchor * ((Train.Electric.Block1Resistance + Train.Electric.Block2Resistance)^2)
		
		-- Apply moment
		Train.FrontBogey.MotorForce = 33000
		Train.FrontBogey.MotorPower = (Moment13 + Moment24) / 2
		Train.FrontBogey.Reversed = false
		Train.RearBogey.MotorForce  = 33000
		Train.RearBogey.MotorPower  = (Moment13 + Moment24) / 2
		Train.RearBogey.Reversed = true
		
		print(E13+E24,totalV,rotationRate,magneticFlux13,Train.FrontBogey.Speed,Train.FrontBogey.Acc)
		print(Format("N %d  I = %.1f A  V = %.1f V  M = %.4f  P = %.1f w",Train.RheostatController.Position,Ianchor,MVoltage,Moment13,Presistance))
	end
end
